name: tesseract
description: A flutter plugin for tesseract based on Android Tesseract and IOS SiwftyTesseract. It has unicode (UTF-8) support, and can recognize more than 100 languages.
version: 0.0.8
homepage: https://github.com/sikandernoori/tesseract

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hunaindev.tesseract
        pluginClass: TesseractPlugin
      ios:
        pluginClass: TesseractPlugin
